import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "../components/header/page";
import Footer from "../components/footer/page";
import { CartProvider } from "@/context/CartContext";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // pick the weights you need
  variable: "--font-poppins", // optional: lets you use it in Tailwind
});


export const metadata: Metadata = {
  title: "EECS 4413",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}`} 
      >
        <CartProvider>
        <Header/>
        {children}
        <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
